name: CreativoLive
favicon: null
layout_spectrum: 0.4749154148157686
typography_spectrum: 0.1704643126577139
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8736754965502769
  lightness: 0.6648535644635558
  saturation: 0.8776763516943902
  rhythmicContrast: 0.8545438924338669
purpose: []
